# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90a9b510827dae9993be63c249d07b18"
name = "Metafield adjustments"
handle = "metafield-adjustments"
application_url = "https://vote-downloaded-summer-governor.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products_create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://vote-downloaded-summer-governor.trycloudflare.com/auth/callback", "https://vote-downloaded-summer-governor.trycloudflare.com/auth/shopify/callback", "https://vote-downloaded-summer-governor.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
